In [1]:
import numpy as np
print("Hello world")

Hello world


# My First Attempt to write Python Code on Jupyter Notebook

In [2]:
def add_numbers(a,b):
    """
    Add Two Numbers Together
    
    Returns
    ------
    the_sum: type of arguments

    Args:
        a (_type_): number
        b (_type_): number
    """
    
    return a + b

add_numbers(2,12)

14

In [3]:
# tup = (4,5,6)

# # print(tup)

# tup = 4,5,6

# print(tup)

tup = tuple('string')
print(tup)

tup = (4,5,6)

a , b , c = tup

print(a,b,c)

('s', 't', 'r', 'i', 'n', 'g')
4 5 6


In [4]:
tup = 4, 5, (6, 7)
print(tup)

(4, 5, (6, 7))


In [5]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
 
for a , b , c in seq:
    print('a={0}, b={1}, c={2}'.format(a, b, c))

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [6]:
values = 1 , 2 , 3 , 4 , 5
a,b, *rest = values

print(a,b , rest)

1 2 [3, 4, 5]


In [7]:

x = [[1,2,3],[4,5,6] ,[7,1,0]]

In [8]:
arr = np.array(x)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [9]:
arr.sum(axis=0)

array([12,  8,  9])

In [10]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [11]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [12]:
arr.ndim

2

In [13]:
arr.size

9

In [14]:
arr.nbytes

36

In [15]:
one = np.array([1,2,3])

In [16]:
one.argmax()

2

In [17]:
one.argmin()

0

In [18]:
one.argsort()

array([0, 1, 2], dtype=int64)

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr.argmin()


0

In [21]:
arr.argmax()


8

In [22]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2 = np.array([[2, 3, 3],
       [8, 5, 12],
       [7, 8, 9]])

In [26]:
arr + arr2

array([[ 3,  5,  6],
       [12, 10, 18],
       [14, 16, 18]])

In [27]:
arr.min()

1

In [28]:
arr2.sum()

57

In [29]:
np.where(arr > 5, 0, 1)

array([[1, 1, 1],
       [1, 1, 0],
       [0, 0, 0]])

In [30]:
np.where(arr2>2
         )

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
np.count_nonzero(arr)

9

In [ ]:
import sys

In [ ]:
py_ar = [0,4,55,2]

In [ ]:
np_arr = np.array(py_ar)

In [ ]:
sys.getsizeof(1) * len(py_ar)

112

In [ ]:
np_arr.itemsize * np_arr.size

16